### ISSUE TITLE
Problem with bind default value

### ISSUE THREAD

**Issue by nsams** [alexeysolonets/extjs-mvvm-extensions#1]
In this grid+form example disabling the form using bind works as it should:

https://fiddle.sencha.com/#fiddle/19r1

Now I want a ViewModel for my grid for the reasons you explained here http://developers-club.com/posts/266773/ and added your Bindable override:

https://fiddle.sencha.com/#fiddle/19qr

Now the initial disabled isn't correct anymore. Once you select a row and clear the selection it works however.

**Comment by alsolonets** [comment]
@nsams thank you for your response, I will review this problem next week and let you know about the solution

**Comment by alsolonets** [comment]
@nsams fixed! Thank you for letting me know. The problem was that publishing initial state didn't notify parent ViewModel. I made the code simpler and now it works better:
https://fiddle.sencha.com/#fiddle/1a3h

offtopic. What is developers-club.com? I didn't publish my article there, also I cannot open it (maybe my IP is blocked). I found it in Google cache and it looks like it was copy-pasted from Google Translate. Maybe I should write an article in English or at least better readme.md :)

**Comment by nsams** [comment]
Thank you, your fix is working.

However it introduces a new issue for me: when I set publishes: ['store'] for Ext.grid.Panel the grid doesn't load anymore. https://fiddle.sencha.com/#fiddle/1a4h

The reason why I do that is that I have a viewModel for the grid and so a paging toolbar can bind to the grids's store - whithout having to be configured from outside.

developers-club.com I found thru google - and although it was pretty poor translation I liked it and found the code on github. You should probably translate it properly...

**Comment by alsolonets** [comment]
@nsams this probably happens because `store` is a pseudo-config (defined other way rather then `config: {}` notation). For your purpose you can try this override
https://gist.github.com/alexeysolonets/ce98236ff2906f3aa73e886663b0754e

**Comment by nsams** [comment]
Ok, thank you for the support
